-- seq ist der Cursor des Offline-Sync: der Client merkt sich den zuletzt
-- gesehenen Wert und fragt spaeter alles Groessere ab. Die Sequenz muss deshalb
-- monoton steigen. GENERATED BY DEFAULT (statt ALWAYS) haelt die Spalte
-- beschreibbar, falls jemals Daten uebernommen werden muessen.
CREATE TABLE change_log (
  seq INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  project_id TEXT NOT NULL,
  op TEXT NOT NULL,
  changed_at TEXT NOT NULL DEFAULT poi_now_iso()
);

CREATE INDEX idx_changelog_project_seq ON change_log(project_id, seq);
